"""
Test what HTML is actually being generated by the callback
"""
from app import render_threat_history_table, get_combined_history
from dash import html
import json

print("\n" + "="*80)
print("DEBUGGING TABLE RENDERING - CHECKING EXACT HTML OUTPUT")
print("="*80)

# Get the raw callback output
result = render_threat_history_table(n_intervals=0, search_value=None)

print(f"\nCallback return type: {type(result)}")
print(f"Children count: {len(result.children) if hasattr(result, 'children') else 'N/A'}")

if hasattr(result, 'children') and len(result.children) > 0:
    table_elem = result.children[0]
    print(f"\nFirst child (Table) type: {type(table_elem)}")
    print(f"Table children: {len(table_elem.children) if hasattr(table_elem, 'children') else 'N/A'}")
    
    # Get thead
    if hasattr(table_elem, 'children') and len(table_elem.children) > 0:
        thead = table_elem.children[0]
        print(f"\nThead type: {type(thead)}")
        print(f"Thead children: {len(thead.children) if hasattr(thead, 'children') else 'N/A'}")
        
        # Get tbody
        if len(table_elem.children) > 1:
            tbody = table_elem.children[1]
            print(f"\nTbody type: {type(tbody)}")
            print(f"Tbody rows: {len(tbody.children) if hasattr(tbody, 'children') else 'N/A'}")
            
            # Check first row
            if hasattr(tbody, 'children') and len(tbody.children) > 0:
                first_row = tbody.children[0]
                print(f"\nFirst row type: {type(first_row)}")
                print(f"First row cells: {len(first_row.children) if hasattr(first_row, 'children') else 'N/A'}")
                
                # Check first row cells
                if hasattr(first_row, 'children'):
                    for idx, cell in enumerate(first_row.children[:3]):
                        print(f"\n  Cell {idx}:")
                        print(f"    Type: {type(cell)}")
                        print(f"    Content: {cell.children if hasattr(cell, 'children') else str(cell)}")
                        print(f"    Style: {cell.style if hasattr(cell, 'style') else 'N/A'}")

# Also check raw data
print("\n\n" + "="*80)
print("RAW DATA SOURCE")
print("="*80)
data = get_combined_history(3)
print(f"\nData records: {len(data)}")
for i, record in enumerate(data):
    print(f"\nRecord {i+1}:")
    for key in ['type', 'severity', 'source_ip', 'country', 'status']:
        print(f"  {key}: '{record.get(key)}'")
